project:
  type: book
  output-dir: _webpage

execute:
  eval: true
  echo: true
  output: true
  freeze: auto  # auto: during global project renders, re-render only when source changes

book:
  title: "Generalizing the Reason FRS Model"
  author: "Don Boyd and Gang Chen"
  date: today
  date-format: long
  sidebar:
    collapse-level: 1
  chapters:
    - index.qmd # index.qmd must be in the quarto project root folder
    - plan.qmd
    # - part: "Data from SOA and Other External Sources"
    #   chapters:
    #   - external/soa/soa_mortality_rates.qmd
    #   - external/soa/soa_mortality_improvement.qmd


# bibliography: references.bib

# devtools::load_all("./")

# from pendata folder, in powershell, enter ./runall.bat

format:
  html:
    theme: cosmo
    code-fold: true
  # pdf:
  #   documentclass: scrreprt

editor_options:
  chunk_output_type: console


# additional execution options
  # error: false
  # warning: false
  # message: false  # not sure if allowed
  # note: false  # not sure if allowed

# renv-related commands
# renv::snapshot()
# renv::restore()
# renv::update()
# renv::status()
# Sys.getenv("RENV_PATHS_CELLAR") # RENV_PATHS_SOURCE RENV_PATHS_RENV


# useful reminders of quarto commands:
# quarto publish netlify --no-render
# quarto publish netlify --no-browser --no-prompt
# quarto publish netlify --no-render --no-browser --no-prompt
# quarto publish quarto-pub --no-render --no-browser --no-prompt

# boyd-mta202324.netlify.app


# possibly use this at start of each doc??
# ---
# output: html_document
# editor_options:
#   chunk_output_type: console
# ---


